#!/usr/bin/env node
// build.js — Scans content/writeups/ and content/notes/ for .md files,
// parses their frontmatter, and generates data.js for the site.

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const WRITEUPS_DIR = path.join(ROOT, 'content', 'writeups');
const NOTES_DIR = path.join(ROOT, 'content', 'notes');
const OUTPUT = path.join(ROOT, 'data.js');

function parseFrontmatter(filePath) {
  const raw = fs.readFileSync(filePath, 'utf-8');
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!match) {
    console.warn(`⚠ No frontmatter in ${path.basename(filePath)}, skipping.`);
    return null;
  }

  const meta = {};
  match[1].split('\n').forEach(line => {
    const idx = line.indexOf(':');
    if (idx === -1) return;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    // Strip surrounding quotes
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    meta[key] = val;
  });

  return {
    title: meta.title || 'Untitled',
    category: meta.category || 'post',
    date: meta.date || '2025-01-01',
    excerpt: meta.excerpt || '',
    tags: (meta.tags || '').split(',').map(t => t.trim()).filter(Boolean)
  };
}

function scanDir(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .map(f => parseFrontmatter(path.join(dir, f)))
    .filter(Boolean)
    .sort((a, b) => new Date(b.date) - new Date(a.date));
}

const writeups = scanDir(WRITEUPS_DIR);
const notes = scanDir(NOTES_DIR);

const output = `// Auto-generated by build.js — do not edit manually.
// To add content, create .md files in content/writeups/ or content/notes/
const writeups = ${JSON.stringify(writeups, null, 2)};

const notes = ${JSON.stringify(notes, null, 2)};
`;

fs.writeFileSync(OUTPUT, output, 'utf-8');
console.log(`✓ Built data.js — ${writeups.length} writeups, ${notes.length} notes`);
