// Auto-generated by build.js — do not edit manually.
// To add content, create .md files in content/writeups/ or content/notes/
const writeups = [
  {
    "title": "HTB: Connected — Full Walkthrough",
    "category": "writeup",
    "date": "2025-06-20",
    "excerpt": "Exploiting SQL injection to RCE on a HackTheBox machine, covering enumeration through privilege escalation.",
    "tags": [
      "htb",
      "sqli",
      "rce"
    ],
    "slug": "htb-connected"
  },
  {
    "title": "Abusing Unconstrained Delegation in AD",
    "category": "writeup",
    "date": "2025-05-15",
    "excerpt": "Leveraging unconstrained delegation to compromise a domain controller via Kerberos ticket theft.asdasdasdasdasda",
    "tags": [
      "active-directory",
      "kerberos",
      "delegation"
    ],
    "slug": "unconstrained-delegation"
  },
  {
    "title": "NTLM Relay & Forced Authentication",
    "category": "writeup",
    "date": "2025-05-10",
    "excerpt": "Forcing NTLM authentication callbacks to capture and relay credentials across the network.",
    "tags": [
      "ntlm",
      "relay",
      "credentials"
    ],
    "slug": "ntlm-relay"
  },
  {
    "title": "Nexus Repository — Path Traversal to RCE",
    "category": "writeup",
    "date": "2025-04-22",
    "excerpt": "Exploiting CVE-2024-4956 in Sonatype Nexus Repository Manager for unauthenticated file read.",
    "tags": [
      "cve",
      "nexus",
      "path-traversal"
    ],
    "slug": "nexus-path-traversal"
  }
];

const notes = [
  {
    "title": "AD ACLs Cheatsheet",
    "category": "cheatsheet",
    "date": "2025-06-01",
    "excerpt": "Quick reference for exploiting Active Directory ACL misconfigurations — GenericAll, WriteDACL, and more.",
    "tags": [
      "active-directory",
      "acl",
      "cheatsheet"
    ],
    "slug": "ad-acls-cheatsheet"
  },
  {
    "title": "Linux Privilege Escalation Notes",
    "category": "notes",
    "date": "2025-03-18",
    "excerpt": "Common privesc vectors: SUID binaries, capabilities, cron jobs, PATH hijacking, and kernel exploits.",
    "tags": [
      "linux",
      "privesc",
      "enumeration"
    ],
    "slug": "linux-privesc"
  }
];
